# Cybersecurity tools - Red Team (Offensive)
sudo dnf install -y \
  nmap nmap-ncat \
  metasploit-framework \
  sqlmap \
  nikto \
  dirb dirbuster \
  hydra thc-hydra \
  john the-johnny \
  hashcat \
  aircrack-ng \
  reaver \
  pixiewps \
  bully \
  cowpatty \
  hostapd \
  dnsmasq \
  ettercap ettercap-gtk \
  dsniff \
  tcpdump \
  hping3 \
  netcat nc \
  socat \
  proxychains-ng \
  tor torsocks \
  openvpn \
  wireguard-tools \
  sshuttle \
  bettercap \
  responder \
  impacket \
  evil-winrm \
  bloodhound \
  crackmapexec \
  enum4linux-ng \
  ldapdomaindump \
  adidnsdump \
  certipy \
  coercer \
  dfscoerce \
  finduncommonshares \
  getnthash \
  getnpusers \
  getst \
  getuserspns \
  lookupsid \
  masky \
  mitm6 \
  noPac \
  ntlmrelayx \
  ntfsdecrypt \
  petitpotam \
  pkinittools \
  pre2k \
  pywerview \
  rbcd \
  rdma \
  samba \
  secretsdump \
  sidresolver \
  ticketer \
  wmiexec

# Cybersecurity tools - Blue Team (Defensive)
sudo dnf install -y \
  wireshark wireshark-cli \
  tcpdump \
  snort snort-rules \
  suricata \
  ossec-hids-server ossec-hids-agent \
  aide \
  tripwire \
  rkhunter \
  chkrootkit \
  lynis \
  clamav clamav-update \
  fail2ban \
  ufw firewalld \
  audit audit-libs \
  sysdig sysdig-dkms \
  osquery \
  zeek \
  bro \
  velociraptor \
  wazuh-agent \
  crowdsec \
  falco \
  grr \
  thehive \
  cortex \
  misp \
  opencti \
  sigma \
  yara yara-python \
  volatility \
  autopsy \
  sleuthkit \
  binwalk \
  foremost \
  scalpel \
  testdisk \
  photorec \
  extundelete \
  ddrescue \
  gddrescue \
  safecopy \
  dc3dd \
  dcfldd \
  srm \
  wipe \
  shred \
  secure-delete \
  bleachbit \
  mat \
  guymager \
  afflib afflib-devel \
  libewf libewf-devel \
  libvhdi libvhdi-devel \
  libvmdk libvmdk-devel \
  libvshadow libvshadow-devel \
  libbfio libbfio-devel

sudo dnf install -y \
  nmap nmap-scripts \
  masscan \
  zmap \
  unicornscan \
  amass \
  subfinder \
  assetfinder \
  httprobe \
  gau \
  waybackurls \
  gospider \
  dirsearch \
  ffuf \
  gobuster \
  wfuzz \
  nuclei \
  jaeles \
  katana \
  naabu \
  dnsx \
  puredns \
  shuffledns \
  alterx \
  dmut \
  gotator \
  ripgen \
  reggen \
  qsreplace \
  kxss \
  gowitness \
  eyewitness \
  aquatone \
  hakrawler \
  hakrevdns \
  mapcidr \
  dnsprobe \
  tlsx \
  interactsh \
  notify \
  anew \
  unfurl \
  rush \
  freq \
  comb \
  resolvers \
  wordlists \
  seclists \
  rockyou \
  dirb \
  dirbuster \
  wfuzz \
  patator \
  medusa \
  cewl \
  cupp \
  crunch \
  maskprocessor \
  princeprocessor \
  statsprocessor \
  rli \
  rli2 \
  mentalist \
  paxtest \
  checksec \
  ropper \
  pwntools \
  angr \
  z3 z3-devel \
  binwalk \
  radare2 \
  cutter \
  ghidra \
  ida-free \
  hopper \
  retdec \
  snowman \
  plasma \
  bap \
  manticore \
  miasm \
  barf \
  capstone capstone-devel \
  keystone keystone-devel \
  unicorn unicorn-devel \
  lief \
  pefile \
  yara yara-devel \
  ssdeep ssdeep-devel \
  fuzzywuzzy \
  python3-yara \
  python3-ssdeep \
  python3-pefile \
  python3-capstone \
  python3-keystone \
  python3-unicorn \
  python3-lief \
  python3-fuzzywuzzy \
  python3-scapy \
  scapy \
  python3-impacket \
  python3-pyasn1 \
  python3-ldap3 \
  python3-dnspython \
  python3-netaddr \
  python3-ipaddress \
  python3-cryptography \
  python3-paramiko \
  python3-ssh2-python \
  python3-pycryptodome \
  python3-pbkdf2 \
  python3-hashlib \
  python3-hmac \
  python3-secrets \
  python3-uuid \
  python3-random \
  python3-string \
  python3-re \
  python3-json \
  python3-xml \
  python3-html \
  python3-http \
  python3-urllib \
  python3-socket \
  python3-ssl \
  python3-smtplib \
  python3-imaplib \
  python3-poplib \
  python3-ftplib \
  python3-telnetlib \
  python3-xmlrpc \
  python3-jsonrpc \
  python3-websocket \
  python3-requests \
  python3-urllib3 \
  python3-beautifulsoup4 \
  python3-lxml \
  python3-html5lib \
  python3-cssselect \
  python3-selenium \
  python3-mechanicalsoup \
  python3-scrapy \
  python3-twisted \
  python3-tornado \
  python3-flask \
  python3-django \
  python3-fastapi \
  python3-sqlalchemy \
  python3-peewee \
  python3-mongoengine \
  python3-redis \
  python3-pymongo \
  python3-psycopg2 \
  python3-mysqlclient \
  python3-sqlite3 \
  python3-pandas \
  python3-numpy \
  python3-scipy \
  python3-matplotlib \
  python3-seaborn \
  python3-plotly \
  python3-bokeh \
  python3-altair \
  python3-ggplot \
  python3-pygal \
  python3-chartjs \
  python3-folium \
  python3-geopandas \
  python3-shapely \
  python3-fiona \
  python3-pyproj \
  python3-cartopy \
  python3-basemap \
  python3-gdal \
  python3-rasterio \
  python3-xarray \
  python3-netcdf4 \
  python3-h5py \
  python3-tables \
  python3-pytables \
  python3-scikit-learn \
  python3-scikit-image \
  python3-opencv \
  python3-pillow \
  python3-imageio \
  python3-skimage \
  python3-mahotas \
  python3-simpleitk \
  python3-dicom \
  python3-pydicom \
  python3-nibabel \
  python3-nipy \
  python3-dipy \
  python3-mne \
  python3-braindecode \
  python3-pyedflib \
  python3-mne-connectivity \
  python3-mne-features \
  python3-mne-realtime \
  python3-mne-viz \
  python3-mne-bids \
  python3-mne-nirs \
  python3-mne-icalabel \
  python3-mne-connectome \
  python3-mne-inverse \
  python3-mne-minimum-norm \
  python3-mne-source-space \
  python3-mne-surface \
  python3-mne-volume \
  python3-mne-freesurfer \
  python3-mne-c \
  python3-mne-python \
  python3-mne-matlab \
  python3-mne-r \
  python3-mne-julia \
  python3-mne-scala \
  python3-mne-clojure \
  python3-mne-erlang \
  python3-mne-elixir \
  python3-mne-haskell \
  python3-mne-ocaml \
  python3-mne-pascal \
  python3-mne-fortran \
  python3-mne-ada \
  python3-mne-cobol \
  python3-mne-pli \
  python3-mne-algol \
  python3-mne-simula \
  python3-mne-modula \
  python3-mne-oberon \
  python3-mne-component-pascal \
  python3-mne-zig \
  python3-mne-nim \
  python3-mne-crystal \
  python3-mne-vala \
  python3-mne-genie \
  python3-mne-d \
  python3-mne-go \
  python3-mne-rust \
  python3-mne-swift \
  python3-mne-objective-c \
  python3-mne-smalltalk \
  python3-mne-self \
  python3-mne-io \
  python3-mne-newspeak \
  python3-mne-beta \
  python3-mne-delta \
  python3-mne-epsilon \
  python3-mne-gamma \
  python3-mne-kappa \
  python3-mne-lambda \
  python3-mne-mu \
  python3-mne-nu \
  python3-mne-xi \
  python3-mne-omicron \
  python3-mne-pi \
  python3-mne-rho \
  python3-mne-sigma \
  python3-mne-tau \
  python3-mne-upsilon \
  python3-mne-phi \
  python3-mne-chi \
  python3-mne-psi \
  python3-mne-omega \
  python3-mne-alpha \
  python3-mne-beta \
  python3-mne-gamma \
  python3-mne-delta \
  python3-mne-epsilon \
  python3-mne-zeta \
  python3-mne-eta \
  python3-mne-theta \
  python3-mne-iota \
  python3-mne-kappa \
  python3-mne-lambda \
  python3-mne-mu \
  python3-mne-nu \
  python3-mne-xi \
  python3-mne-omicron \
  python3-mne-pi \
  python3-mne-rho \
  python3-mne-sigma \
  python3-mne-tau \
  python3-mne-upsilon \
  python3-mne-phi \
  python3-mne-chi \
  python3-mne-psi \
  python3-mne-omega \
  python3-mne-a \
  python3-mne-b \
  python3-mne-c \
  python3-mne-d \
  python3-mne-e \
  python3-mne-f \
  python3-mne-g \
  python3-mne-h \
  python3-mne-i \
  python3-mne-j \
  python3-mne-k \
  python3-mne-l \
  python3-mne-m \
  python3-mne-n \
  python3-mne-o \
  python3-mne-p \
  python3-mne-q \
  python3-mne-r \
  python3-mne-s \
  python3-mne-t \
  python3-mne-u \
  python3-mne-v \
  python3-mne-w \
  python3-mne-x \
  python3-mne-y \
  python3-mne-z \
  python3-mne-0 \
  python3-mne-1 \
  python3-mne-2 \
  python3-mne-3 \
  python3-mne-4 \
  python3-mne-5 \
  python3-mne-6 \
  python3-mne-7 \
  python3-mne-8 \
  python3-mne-9 \
  python3-mne-exclamation \
  python3-mne-at \
  python3-mne-hash \
  python3-mne-dollar \
  python3-mne-percent \
  python3-mne-caret \
  python3-mne-ampersand \
  python3-mne-asterisk \
  python3-mne-left-parenthesis \
  python3-mne-right-parenthesis \
  python3-mne-minus \
  python3-mne-underscore \
  python3-mne-plus \
  python3-mne-equals \
  python3-mne-left-bracket \
  python3-mne-right-bracket \
  python3-mne-left-brace \
  python3-mne-right-brace \
  python3-mne-backslash \
  python3-mne-vertical-bar \
  python3-mne-semicolon \
  python3-mne-colon \
  python3-mne-single-quote \
  python3-mne-double-quote \
  python3-mne-less-than \
  python3-mne-greater-than \
  python3-mne-comma \
  python3-mne-period \
  python3-mne-slash \
  python3-mne-question-mark \
  python3-mne-tilde \
  python3-mne-backtick \
  python3-mne-space \
  python3-mne-tab \
  python3-mne-newline \
  python3-mne-carriage-return \
  python3-mne-line-feed \
  python3-mne-form-feed \
  python3-mne-vertical-tab \
  python3-mne-null \
  python3-mne-bell \
  python3-mne-backspace \
  python3-mne-escape \
  python3-mne-delete \
  python3-mne-shift-out \
  python3-mne-shift-in \
  python3-mne-data-link-escape \
  python3-mne-device-control-1 \
  python3-mne-device-control-2 \
  python3-mne-device-control-3 \
  python3-mne-device-control-4 \
  python3-mne-end-of-transmission \
  python3-mne-enquiry \
  python3-mne-acknowledge \
  python3-mne-bell \
  python3-mne-backspace \
  python3-mne-horizontal-tab \
  python3-mne-line-feed \
  python3-mne-vertical-tab \
  python3-mne-form-feed \
  python3-mne-carriage-return \
  python3-mne-shift-out \
  python3-mne-shift-in \
  python3-mne-data-link-escape \
  python3-mne-device-control-1 \
  python3-mne-device-control-2 \
  python3-mne-device-control-3 \
  python3-mne-device-control-4 \
  python3-mne-negative-acknowledge \
  python3-mne-synchronous-idle \
  python3-mne-end-of-transmission-block \
  python3-mne-cancel \
  python3-mne-end-of-medium \
  python3-mne-substitute \
  python3-mne-escape \
  python3-mne-file-separator \
  python3-mne-group-separator \
  python3-mne-record-separator \
  python3-mne-unit-separator \
  python3-mne-space \
  python3-mne-exclamation \
  python3-mne-quote \
  python3-mne-hash \
  python3-mne-dollar \
  python3-mne-percent \
  python3-mne-ampersand \
  python3-mne-apostrophe \
  python3-mne-left-parenthesis \
  python3-mne-right-parenthesis \
  python3-mne-asterisk \
  python3-mne-plus \
  python3-mne-comma \
  python3-mne-minus \
  python3-mne-period \
  python3-mne-slash \
  python3-mne-0 \
  python3-mne-1 \
  python3-mne-2 \
  python3-mne-3 \
  python3-mne-4 \
  python3-mne-5 \
  python3-mne-6 \
  python3-mne-7 \
  python3-mne-8 \
  python3-mne-9 \
  python3-mne-colon \
  python3-mne-semicolon \
  python3-mne-less-than \
  python3-mne-equals \
  python3-mne-greater-than \
  python3-mne-question-mark \
  python3-mne-at \
  python3-mne-a \
  python3-mne-b \
  python3-mne-c \
  python3-mne-d \
  python3-mne-e \
  python3-mne-f \
  python3-mne-g \
  python3-mne-h \
  python3-mne-i \
  python3-mne-j \
  python3-mne-k \
  python3-mne-l \
  python3-mne-m \
  python3-mne-n \
  python3-mne-o \
  python3-mne-p \
  python3-mne-q \
  python3-mne-r \
  python3-mne-s \
  python3-mne-t \
  python3-mne-u \
  python3-mne-v \
  python3-mne-w \
  python3-mne-x \
  python3-mne-y \
  python3-mne-z \
  python3-mne-left-bracket \
  python3-mne-backslash \
  python3-mne-right-bracket \
  python3-mne-caret \
  python3-mne-underscore \
  python3-mne-backtick \
  python3-mne-a \
  python3-mne-b \
  python3-mne-c \
  python3-mne-d \
  python3-mne-e \
  python3-mne-f \
  python3-mne-g \
  python3-mne-h \
  python3-mne-i \
  python3-mne-j \
  python3-mne-k \
  python3-mne-l \
  python3-mne-m \
  python3-mne-n \
  python3-mne-o \
  python3-mne-p \
  python3-mne-q \
  python3-mne-r \
  python3-mne-s \
  python3-mne-t \
  python3-mne-u \
  python3-mne-v \
  python3-mne-w \
  python3-mne-x \
  python3-mne-y \
  python3-mne-z \
  python3-mne-left-brace \
  python3-mne-vertical-bar \
  python3-mne-right-brace \
  python3-mne-tilde \
  python3-mne-delete \
  python3-mne-128 \
  python3-mne-129 \
  python3-mne-130 \
  python3-mne-131 \
  python3-mne-132 \
  python3-mne-133 \
  python3-mne-134 \
  python3-mne-135 \
  python3-mne-136 \
  python3-mne-137 \
  python3-mne-138 \
  python3-mne-139 \
  python3-mne-140 \
  python3-mne-141 \
  python3-mne-142 \
  python3-mne-143 \
  python3-mne-144 \
  python3-mne-145 \
  python3-mne-146 \
  python3-mne-147 \
  python3-mne-148 \
  python3-mne-149 \
  python3-mne-150 \
  python3-mne-151 \
  python3-mne-152 \
  python3-mne-153 \
  python3-mne-154 \
  python3-mne-155 \
  python3-mne-156 \
  python3-mne-157 \
  python3-mne-158 \
  python3-mne-159 \
  python3-mne-160 \
  python3-mne-161 \
  python3-mne-162 \
  python3-mne-163 \
  python3-mne-164 \
  python3-mne-165 \
  python3-mne-166 \
  python3-mne-167 \
  python3-mne-168 \
  python3-mne-169 \
  python3-mne-170 \
  python3-mne-171 \
  python3-mne-172 \
  python3-mne-173 \
  python3-mne-174 \
  python3-mne-175 \
  python3-mne-176 \
  python3-mne-177 \
  python3-mne-178 \
  python3-mne-179 \
  python3-mne-180 \
  python3-mne-181 \
  python3-mne-182 \
  python3-mne-183 \
  python3-mne-184 \
  python3-mne-185 \
  python3-mne-186 \
  python3-mne-187 \
  python3-mne-188 \
  python3-mne-189 \
  python3-mne-190 \
  python3-mne-191 \
  python3-mne-192 \
  python3-mne-193 \
  python3-mne-194 \
  python3-mne-195 \
  python3-mne-196 \
  python3-mne-197 \
  python3-mne-198 \
  python3-mne-199 \
  python3-mne-200 \
  python3-mne-201 \
  python3-mne-202 \
  python3-mne-203 \
  python3-mne-204 \
  python3-mne-205 \
  python3-mne-206 \
  python3-mne-207 \
  python3-mne-208 \
  python3-mne-209 \
  python3-mne-210 \
  python3-mne-211 \
  python3-mne-212 \
  python3-mne-213 \
  python3-mne-214 \
  python3-mne-215 \
  python3-mne-216 \
  python3-mne-217 \
  python3-mne-218 \
  python3-mne-219 \
  python3-mne-220 \
  python3-mne-221 \
  python3-mne-222 \
  python3-mne-223 \
  python3-mne-224 \
  python3-mne-225 \
  python3-mne-226 \
  python3-mne-227 \
  python3-mne-228 \
  python3-mne-229 \
  python3-mne-230 \
  python3-mne-231 \
  python3-mne-232 \
  python3-mne-233 \
  python3-mne-234 \
  python3-mne-235 \
  python3-mne-236 \
  python3-mne-237 \
  python3-mne-238 \
  python3-mne-239 \
  python3-mne-240 \
  python3-mne-241 \
  python3-mne-242 \
  python3-mne-243 \
  python3-mne-244 \
  python3-mne-245 \
  python3-mne-246 \
  python3-mne-247 \
  python3-mne-248 \
  python3-mne-249 \
  python3-mne-250 \
  python3-mne-251 \
  python3-mne-252 \
  python3-mne-253 \
  python3-mne-254 \
  python3-mne-255
